spring:
  datasource:
    url: "jdbc:mysql://localhost/woodong"
    username : "root"
    password : "9764"
    driver-class-name: com.mysql.cj.jdbc.Driver

    spring:
      security:
        user:
          name: user
          password: 1234

    upload:
    directory: C:/capstoneImage



    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html

